exclude: '^$'
fail_fast: true
repos:
- repo: local
  hooks:
    - id: black
      name: black
      stages: [commit]
      language: python
      entry: poetry run black selfsupav
      types: [python]
      language_version: python3.8